# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
on:
  workflow_call:
    inputs:
      pkg-path:
        required: true
        type: string

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install Oracle drivers 
        run: |
          sudo apt-get install -y libaio1 libaio-dev
          wget https://download.oracle.com/otn_software/linux/instantclient/19600/instantclient-basic-linux.x64-19.6.0.0.0dbru.zip -O oic_basic.zip && unzip oic_basic.zip && rm oic_basic.zip
          wget https://download.oracle.com/otn_software/linux/instantclient/19600/instantclient-sdk-linux.x64-19.6.0.0.0dbru.zip -O oic_sdk.zip && unzip oic_sdk.zip && rm oic_sdk.zip
          export OCI_LIB=$(pwd)/instantclient_19_6
          export LD_LIBRARY_PATH=$(pwd)/instantclient_19_6

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rcmdcheck, any::covr, any::goodpractice, any::lintr
          working-directory: ${{ inputs.pkg-path }}

      - uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: ${{ inputs.pkg-path }}

      - name: Code coverage
        run: covr::package_coverage()
        shell: Rscript {0}
        working-directory: ${{ inputs.pkg-path }}

      - name: Good practices
        run: |
          goodpractice::gp(checks = c(
            "cyclocomp",
            "no_import_package_as_a_whole",
            "no_export_pattern"
          ))
        shell: Rscript {0}
        working-directory: ${{ inputs.pkg-path }}

      - name: Lint
        run: |
          library(lintr)
          lint_package(linters = with_defaults(object_name_linter("camelCase"), line_length_linter(160L), object_length_linter(length = 60L)))
        shell: Rscript {0}
        working-directory: ${{ inputs.pkg-path }}
