# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
on:
  workflow_call:
    inputs:
      pkg-path:
        required: true
        type: string

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2
        with:
          working-directory: ${{ inputs.pkg-path }}
