# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release-event-release
on:
  release:
    types: [published]

name: build-and-release

jobs:
  buildRPkgs:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: build archives
        run: make rpkgs
      - name: Create docker image 
        run: make docker

  buildDocker:
    needs: buildRPkgs
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-buildx-action@v2